dist: trusty
language: node_js
node_js:
  - '6'
  - '8'
  - '10'

sudo: false

notifications:
  email:
    on_success: change
    on_failure: always

cache: yarn

jobs:
  include:
    - stage: Test
      name: Lint
      script: yarn run lint
    - stage: Test
      name: Lint
      script:
        - yarn run test --coverage
        - cat coverage/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"
    - stage: Build
      name: Build
      script:
        - yarn run build
        - yarn run bundlesize
    - stage: E2E
      name: Cypress
      script: npx cypress run
